### ISSUE TITLE
Make processing steps and psa files configurable in config.toml

### ISSUE THREAD

**Issue by sspagnol** [jmassaims/sbe_ctd_proc#26]
Processing steps and associated psa flies are hardwired in process.py. Can the sequence be setup in config.toml (example below) where 
```step``` is same as the function to be called, ```psa``` the associated psa filename, ```append``` the character to append to filename. Assume you can then just iterate over process_sequence calling functions as required.

```toml
# sequence of processing steps
# processing order is as listed

[[process_sequence]]
step = "filter"
psa = "Filter.psa"
append = "F"

[[process_sequence]]
step = 'align_ctd'
psa = "AlignCTD.psa"
append = "A"

[[process_sequence]]
step = 'cell_thermal_mass'
psa = "CellTM.psa"
append = "C"

[[process_sequence]]
step = 'loop_edit'
psa = "LoopEditIMOS.psa"
append = "L"

[[process_sequence]]
step = 'derive'
psa = "DeriveIMOS.psa"
append = "D"

[[process_sequence]]
step = 'bin_avg'
psa = "BinAvgIMOS.psa"
append = "B"
```
